TOT/Controllers/BuyerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using TOT.BAL;
using TOT.Models;

namespace TOT.Controllers
{
    public class BuyerController : Controller
    {
        [AllowAnonymous]
        public ActionResult ActivateAccount(string buyerID)
        {
            BuyerModel model = new BuyerModel();
            CompanyModel objCompanyModel = new CompanyModel();

            string sBID = Helper.Decrypt(HttpUtility.UrlDecode(buyerID));

            model = CompanyRepository.GetBuyerDetail(sBID);

            if (model != null)
            {
                if (model.CompanyID == "0")
                    ViewBag.CompanyName = model.CompanyName;
                else
                {
                    objCompanyModel = CompanyRepository.GetCompanyDetails(model.CompanyID);
                    ViewBag.CompanyName = (objCompanyModel != null) ? objCompanyModel.CompanyName : "";
                }

                ViewBag.ProfileCompleted = (model.Password == "" || model.Password == null) ? "0" : "1";
            }
            else
                ViewBag.ProfileCompleted = "1";

            ViewBag.buyerID = sBID;
            ViewBag.CompanyName = (model != null) ? ((model.CompanyName == "" || model.CompanyName == null) ? "" : model.CompanyName) : "";
            ViewBag.AcVerified = "0";
            ViewBag.EmailID = "";
            ViewBag.Pwd = "";

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult ActivateAccount(BuyerModel model)
        {
            if (string.IsNullOrWhiteSpace(model.Password))
            {
                ModelState.AddModelError("PasswordReq", "Please enter password");
            }
            else if (model.Password.Length < 6)
            {
                ModelState.AddModelError("PasswordReq", "Password should be atleast 6 characters");
            }
            else
            {
                var result = CompanyRepository.ActivateBuyer(model);
                //model.Password = "";
                //return RedirectToAction("ProfileCompleted", "Buyer");

                BuyerModel objBuyerModel = CompanyRepository.GetBuyerDetail(model.UserID);

                ViewBag.ProfileCompleted = "-1";
                ViewBag.AcVerified = "1";
                ViewBag.EmailID = (objBuyerModel != null) ? objBuyerModel.EmailID : "";
                ViewBag.Pwd = model.Password;

                return View(model);
            }

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult RecreateBuyerByKey(string buyerID, string userUID)
        {
            BuyerModel model = new BuyerModel();
            BuyerModel objBuyerModel = new BuyerModel();
            CompanyModel objCompanyModel = new CompanyModel();

            model = CompanyRepository.GetBuyerDetail(buyerID);

            objBuyerModel.UserID = userUID;
            objBuyerModel.City = model.City;
            objBuyerModel.CompanyID = model.CompanyID;
            objBuyerModel.CompanyName = model.CompanyName;
            objBuyerModel.ContactName = model.ContactName;
            objBuyerModel.DeviceType = model.DeviceType;
            objBuyerModel.EmailID = model.EmailID;
            objBuyerModel.Password = model.Password;
            objBuyerModel.FirstName = model.FirstName;
            objBuyerModel.IsActive = model.IsActive;
            objBuyerModel.IsAuthenticated = model.IsAuthenticated;
            objBuyerModel.IsDeleted = model.IsDeleted;
            objBuyerModel.IsNotificationsRequired = model.IsNotificationsRequired;
            objBuyerModel.JobTitle = model.JobTitle;
            objBuyerModel.LastName = model.LastName;
            objBuyerModel.Phone = model.Phone;
            objBuyerModel.UserType = model.UserType;
            objBuyerModel.DateCreated = model.DateCreated;
            objBuyerModel.DateUpdated = model.DateUpdated;

            bool bInsertResult = CompanyRepository.InsertBuyerWithKey(objBuyerModel, userUID);

            bool bDeleteResult = CompanyRepository.DeleteBuyerPermanently(buyerID);

            if (bInsertResult && bDeleteResult)
                return Json(new { status = "1", message = "" }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { status = "0", message = "Something went wrong. Please contact administrator." }, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult ProfileCompleted()
        {
            return View();
        }
    }
}

TOT/Views/Buyer/ActivateAccount.cshtml
@model TOT.Models.BuyerModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Trendontap" />

    <!-- Stylesheets
    ============================================= -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/Styles/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/style.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/dark.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/font-icons.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/animate.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/magnific-popup.css" type="text/css" />

    <link rel="stylesheet" href="~/Styles/responsive.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <!-- Document Title
    ============================================= -->
    <title>Complete Profile | Trendontap</title>

    <style type="text/css">
        .automargin {
            margin-left: auto;
            margin-right: auto;
            width: 120px;
        }

        .greenStatus {
            background: url(../../images/sprite.png) no-repeat -3px -3px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .searchIcon {
            background: url(../../images/sprite.png) no-repeat -3px -46px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .editIcon {
            background: url(../../images/sprite.png) no-repeat -3px -93px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .removeIcon {
            background: url(../../images/sprite.png) no-repeat -3px -139px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .button-blue {
            background: #0a6cd9;
        }

            .button-blue:hover {
                background: #0550a3;
            }

        .questrial {
            font-family: 'Questrial', sans-serif;
        }


        .pagination > li > a, .pagination > li > span, .pagination > li > a:hover, .pagination > li > span:hover, .pagination > li > a:focus, .pagination > li > span:focus {
            color: #337ab7;
        }

        .btn-no-bdr {
            border-color: #f5f5f5;
            text-transform: uppercase;
            font-size: 11px;
            margin-top: 4px;
        }

        .btn-save {
            font-size: 0.85em;
            padding-bottom: 2.5em;
            margin-bottom: 2.5em;
            margin-left: auto;
            margin-right: auto;
        }

        .img-circle {
            margin: 2.em auto;
        }

        .ok {
            margin-top: 32px;
            font-size: 20px;
            color: #060;
        }

        #content {
            width: 80%;
            margin: auto;
            margin-top: 10px;
            border-radius: 5px;
            padding: 0;
        }

            #content h1 {
                margin: 20px 0;
                padding: 0;
                margin-left: 0;
            }



        #content {
            width: 95%;
        }

        .container {
            width: 100%;
        }



        div#Inhf {
            width: 0px;
            height: 0px;
            overflow: hidden;
        }
    </style>
</head>

<body class="stretched" style="background:#1f2532;">
    <!-- Content
    ============================================= -->
    <section id="content">
        <div class="container">
            <h1 align="center">Please start by completing<br> your profile</h1>
            <div>
                <div class="row" style="width:100%;">
                    <!--<div class="col-sm-1" style="background:orange;">&nbsp;</div>--> <!-- spacer -->
                    @Html.AntiForgeryToken()
                    @using (Html.BeginForm("ActivateAccount", "Buyer", new { userId = ViewBag.buyerID }, FormMethod.Post, new { @class = "login_form" }))
                    {
                        <div class="col-sm-2" style="">&nbsp;</div>
                        <div class="col-sm-8">

                            <div class="row">
                                <div class="col-xs-offset-1 col-xs-10">
                                    <div class="form-group">
                                        <label for="name">Full Name</label>
                                        @Html.TextBoxFor(m => m.ContactName, new { @class = "form-control", disabled = "disabled" })
                                    </div>
                                </div> <!-- 6 -->
                                <div class="col-xs-1 ok"><i class="icon-ok-sign"></i></div>
                            </div> <!-- row 1-->

                            <div class="row">
                                <div class="col-xs-offset-1 col-xs-10">
                                    <div class="form-group">
                                        <label for="name">Company Name</label>
                                        @Html.TextBox("CompanyName", (string)ViewBag.CompanyName, new { @class = "form-control", disabled = "disabled" })
                                    </div>
                                </div> <!-- 6 -->
                                <div class="col-xs-1 ok"><i class="icon-ok-sign"></i></div>
                            </div> <!-- row 2 -->

                            <div class="row">
                                <div class="col-xs-offset-1 col-xs-10">
                                    <div class="form-group">
                                        <label for="name">Email</label>
                                        @Html.TextBoxFor(m => m.EmailID, new { @class = "form-control", disabled = "disabled" })
                                    </div>
                                </div> <!-- 6 -->
                                <div class="col-xs-1 ok"><i class="icon-ok-sign"></i></div>
                            </div> <!-- row 3-->

                            <div class="row">
                                <div class="col-xs-offset-1 col-xs-10">
                                    <div class="form-group">
                                        <label for="name">Phone</label>
                                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", @placeholder = "+44 7965898745" })
                                    </div>
                                </div> <!-- 6 -->
                                <div class="col-xs-1 ok">&nbsp;</div>
                            </div> <!-- row 4-->

                            <div class="row">
                                <div class="col-xs-offset-1 col-xs-10">
                                    <div class="form-group">
                                        <label for="name">Password</label>
                                        @Html.PasswordFor(m => m.Password, new { @type = "password", @class = "form-control not-dark", @placeholder = "Password" })
                                        @Html.ValidationMessage("PasswordReq", new { @style = "color:red;" })
                                    </div>
                                </div> <!-- 6 -->
                                <div class="col-xs-1 ok">&nbsp;</div>

                            </div> <!-- row 5-->
                            <br />
                            <div class="row">
                                <div class="col-sm-5">&nbsp;</div>
                                <div class="col-sm-2">
                                    <input type="submit" class="button button-3d btn-save btn-primary button-blue nomargin" id="" name="" value="Save & Continue">
                                </div>
                                <div class="col-sm-5">&nbsp;</div>
                            </div> <!--row -->

                        </div> <!-- 7 -->
                        <div class="col-sm-2" style="">&nbsp;</div>
                        <div class="col-sm-4" style="display:none;">
                            <p><br><a href="#"><img src="../../Images/addPhoto.png" id="imgLogo" alt="Photo" class="img-circle1" onclick="jQuery('#file').click()"></a></p>
                        </div>
                        <div id="Inhf">
                            <input type="file" id="file" name="file" />
                        </div>
                    }
                    <!-- 4 -->
                </div> <!-- row -->
            </div>
        </div>
        <!-- container ->

        </section><!-- #content end -->
        <!-- #wrapper end -->
        <!-- Go To Top
        ============================================= -->
        <div id="gotoTop" class="icon-angle-up"></div>

        <!-- External JavaScripts
        ============================================= -->
        <script type="text/javascript" src="~/Scripts/jquery.js"></script>
        <script type="text/javascript" src="~/Scripts/plugins.js"></script>

        <!-- Footer Scripts
        ============================================= -->
        <script type="text/javascript" src="~/Scripts/functions.js"></script>

        <script>
            jQuery("#tabs-profile").on("tabsactivate", function (event, ui) {
                jQuery('.flexslider .slide').resize();
            });
        </script>

        <script src="https://www.gstatic.com/firebasejs/5.3.0/firebase.js"></script>

        <script>
            // Initialize Firebase
            var config = {
                apiKey: "@System.Configuration.ConfigurationManager.AppSettings["FireBaseAPIKey"].ToString()",
                authDomain: "@System.Configuration.ConfigurationManager.AppSettings["FireBaseAuthDomain"].ToString()",
                databaseURL: "@System.Configuration.ConfigurationManager.AppSettings["FireBaseDBURL"].ToString()",
                projectId: "@System.Configuration.ConfigurationManager.AppSettings["FireBaseProjectID"].ToString()",
                storageBucket: "@System.Configuration.ConfigurationManager.AppSettings["FireBaseStorageBucket"].ToString()",
                messagingSenderId: "@System.Configuration.ConfigurationManager.AppSettings["FireBaseMessagingSenderID"].ToString()"
            };
            firebase.initializeApp(config);

            $(document).ready(function () {
                if(@ViewBag.ProfileCompleted == 1)
                {
                    alert("You have already set up your profile. Please download the app & proceed to login!");

                    window.location = "@Url.Action("ProfileCompleted", "Buyer")";
                }
                else
                {
                    if(@ViewBag.AcVerified == 1)
                    {
                        var email = "@ViewBag.EmailID";
                        var pwd = "@ViewBag.Pwd";

                        if(email != "" && pwd != "")
                        {
                            firebase.auth().createUserWithEmailAndPassword(email, pwd)
                            .then(function(userRecord) {

                                $.ajax({
                                    url: '@Url.Action("RecreateBuyerByKey", "Buyer")',
                                    type: 'POST',
                                    data: '{"buyerID":' + JSON.stringify('@Request.QueryString["userID"]') + ', "userUID":' + JSON.stringify(userRecord.user.uid) + '}',
                                    contentType: "application/json",
                                    dataType: "json",
                                    success: function (result) {
                                        console.log(result);

                                        window.location = '@Url.Action("ProfileCompleted", "Buyer")';
                                    },
                                    error: function (jqXHR, textStatus, errorThrown) {
                                        console.log("Error is below > ");
                                        console.log(jqXHR);
                                        console.log("Status > " + textStatus);
                                        console.log("errorThrown > " + errorThrown);
                                        //alert("Error");
                                    }
                                });
                            })
                            .catch(function (error) {
                                // Handle Errors here.
                                var errorCode = error.code;
                                var errorMessage = error.message;
                                // ...

                                alert(error.message);
                            });
                        }
                        else
                        {
                            console.log("Invalid email or password for creating firebase user account");
                        }
                    }
                }
            });
        </script>
</body>
</html>

TOT/Views/Buyer/ProfileCompleted.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Trendontap" />

    <!-- Stylesheets
    ============================================= -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/Styles/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/style.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/dark.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/font-icons.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/animate.css" type="text/css" />
    <link rel="stylesheet" href="~/Styles/magnific-popup.css" type="text/css" />

    <link rel="stylesheet" href="~/Styles/responsive.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <!-- Document Title
    ============================================= -->
    <title>Complete Profile | Trendontap</title>

    <style type="text/css">
        .automargin {
            margin-left: auto;
            margin-right: auto;
            width: 120px;
        }

        .greenStatus {
            background: url(../../images/sprite.png) no-repeat -3px -3px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .searchIcon {
            background: url(../../images/sprite.png) no-repeat -3px -46px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .editIcon {
            background: url(../../images/sprite.png) no-repeat -3px -93px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .removeIcon {
            background: url(../../images/sprite.png) no-repeat -3px -139px;
            width: 25px;
            height: 25px;
            float: left;
            cursor: pointer;
        }

        .button-blue {
            background: #0a6cd9;
        }

            .button-blue:hover {
                background: #0550a3;
            }

        .questrial {
            font-family: 'Questrial', sans-serif;
        }


        .pagination > li > a, .pagination > li > span, .pagination > li > a:hover, .pagination > li > span:hover, .pagination > li > a:focus, .pagination > li > span:focus {
            color: #337ab7;
        }

        .btn-no-bdr {
            border-color: #f5f5f5;
            text-transform: uppercase;
            font-size: 11px;
            margin-top: 4px;
        }

        .ok {
            margin-top: 32px;
            font-size: 20px;
            color: #060;
        }

        #content {
            width: 80%;
            margin: auto;
            margin-top: 10px;
            border-radius: 5px;
            padding: 0;
        }

            #content h1 {
                margin: 20px 0;
                padding: 0;
                margin-left: 0;
            }
    </style>
</head>

<body class="stretched" style="background:#1f2532;">
    <!-- Content
    ============================================= -->
    <section id="content">
        <div class="container">
            <h1 align="center">Your profile has been completed !!</h1>
            <p align=center> You now need to download the mobile app and login using your details to start accessing your trends with a tap of a finger.</br> Available on iPhone and Android. </p>
            <p align=center><img src="../../images/download-app.png" alt=""></p>
            <p align=center>
                <a href="https://itunes.apple.com/ca/app/trendontap/id1203856766?mt=8" target="_blank"><img src="../../images/button_appstore.png" alt=""></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="../../images/button_playstore.png" alt="">
            </p>
            <div style="display:none;">
                <p align=center> If you have downloaded the app, click below to add your trends and manage your profile. </br> Alternatively you can also manage and your trends through the App. <p>
                <p align="center"><button class="button button-3d button-blue nomargin" id="" name="" value="" onClick="">Let's Begin!</button></p>
            </div>
        </div>
        <!-- container ->

        </section><!-- #content end -->
        </div><!-- #wrapper end -->
        <!-- Go To Top
        ============================================= -->
        <div id="gotoTop" class="icon-angle-up"></div>

        <!-- External JavaScripts
        ============================================= -->
        <script type="text/javascript" src="~/Scripts/jquery.js"></script>
        <script type="text/javascript" src="~/Scripts/plugins.js"></script>

        <!-- Footer Scripts
        ============================================= -->
        <script type="text/javascript" src="~/Scripts/functions.js"></script>

        <script>
            jQuery("#tabs-profile").on("tabsactivate", function (event, ui) {
                jQuery('.flexslider .slide').resize();
            });
        </script>

</body>
</html>